name: Publish

on:
  release:
    types: [ published ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install b2
        run: |
          python -m pip install b2

      - name: b2 login
        run: b2 authorize-account ${B2_ID} ${B2_KEY}
        env:
          B2_ID: ${{ secrets.B2_ID }}
          B2_KEY: ${{ secrets.B2_KEY }}

      - name: show release version
        run: echo "${{ env.VERSION }}"
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: download mac version
        run: b2 download-file-by-name qiyutechseo "${{ env.VERSION }}/darwin/zip/darwin/x64/seo-darwin-x64-${{ env.VERSION }}.zip" mac.zip
        env:
          VERSION: ${{ github.event.ref }}

      - name: release mac version
        uses: softprops/action-gh-release@v1
        with:
          files: mac.zip

      - name: download windows version
        run: b2 download-file-by-name qiyutechseo "${{ env.VERSION }}/win32/squirrel.windows/x64/seo-${{ env.VERSION }} Setup.exe" seo_setup.exe
        env:
          VERSION: ${{ github.event.ref }}

      - name: release windows version
        uses: softprops/action-gh-release@v1
        with:
          files: seo_setup.exe

      - name: download linux deb version
        run: b2 download-file-by-name qiyutechseo "${{ env.VERSION }}/linux/deb/x64/seo_${{ env.VERSION }}_amd64.deb" seo_amd64.deb
        env:
          VERSION: ${{ github.event.ref }}

      - name: release linux debian version
        uses: softprops/action-gh-release@v1
        with:
          files: seo_amd64.deb

      - name: download linux rpm version
        run: b2 download-file-by-name qiyutechseo "${{ env.VERSION }}/linux/rpm/x64/seo-${{ env.VERSION }}-1.x86_64.rpm" seo.x86_64.rpm
        env:
          VERSION: ${{ github.event.ref }}

      - name: release linux rpm version
        uses: softprops/action-gh-release@v1
        with:
          files: seo.x86_64.rpm
